%pip install GoogleNews

from GoogleNews import GoogleNews
import pandas as pd

googlenews = GoogleNews()
googlenews.set_lang('pt')
googlenews.set_period('5d')

googlenews.clear()

googlenews.search('Whinderson')

googlenews.total_count()

pesquisa_whinderson = googlenews.results()

df_whinderson = pd.DataFrame(pesquisa_whinderson)

display(df_whinderson)

title	media	date	datetime	desc	link	img
0	Venda dos ingressos para o show do Whindersson...	GP1	á 1 hora	None	Os ingressos para o show de despedida de Whind...	https://www.gp1.com.br/pi/piaui/noticia/2022/5...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
1	THE: Whindersson Nunes abre venda de ingressos...	Meio Norte	á 2 horas	None	O comediante anunciou que a apresentação na ca...	https://www.meionorte.com/entretenimento/famos...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
2	Venda de ingressos para o show de Whindersson ...	Portal O Dia	á 2 horas	None	Começa hoje (10) a partir das 18 horas a venda...	https://portalodia.com/noticias/teresina/venda...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
3	Whindersson Nunes abre sessão extra de apresen...	A Redação	á 13 horas	None	(Foto: divulgação)A Redação Goiânia – Whinders...	https://www.aredacao.com.br/cultura/167823/con...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
4	Ex de Whindersson Nunes desabafa sobre o prime...	ENTRETÊ by SpinOff	á 14 horas	None	Ex-noiva do humorista Whindersson Nunes, Maria...	https://spinoff.com.br/entrete/maria-lina-reco...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
5	“Meu namorado”, diz Whindersson Nunes sobre Ne...	Tecnonoticias	á 17 horas	None	Neymar Jr. encontrou o humorista Whindersson N...	https://tecnonoticias.com.br/entretenimento/me...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
6	Whindersson Nunes ganha presente de Neymar apó...	GP1	á 20 horas	None	O humorista piauiense Whindersson Nunes se enc...	https://www.gp1.com.br/entretenimento/noticia/...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
7	Whindersson Nunes encontra Neymar Jr. e ganha ...	Folha Vitória	á 22 horas	None	Encontro de milhões! No último domingo, dia 8,...	https://www.folhavitoria.com.br/entretenimento...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
8	Whindersson Nunes posa com Neymar em Paris e b...	MS Notícias	á 22 horas	None	"Ganhei a do jogo. Fofinho, @neymarjr. Muito m...	https://www.msnoticias.com.br/variedades/whind...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
9	Neymar tem relação exposta com foto e famoso c...	TV Foco	á 23 horas	None	No último domingo, 08, Whindersson Nunes ganho...	https://www.otvfoco.com.br/neymar-tem-relacao-...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...

googlenews.clear()

pesquisa_lula = googlenews.search('Lula')

googlenews.total_count()

pesquisa_lula = googlenews.result()

df_lula = pd.DataFrame(pesquisa_lula)

display(df_lula)

title	media	date	datetime	desc	link	img
0	Frase do dia	VEJA	á 1 hora	None	“Bolsonaro, seus dias estão contados. Não adia...	https://veja.abril.com.br/coluna/matheus-leita...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
1	Lula age para minar Ciro e PT oferece apoio no...	Folha Vitória	á 1 hora	None	Nos últimos dias, o próprio Lula entrou nas ar...	https://www.folhavitoria.com.br/politica/notic...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
2	Kassab, em Minas Gerais, prefere três senadore...	Metrópoles	á 1 hora	None	Se acontecer, ainda se arrastará por mais algu...	https://www.metropoles.com/blog-do-noblat/rica...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
3	Bancada do PSD de Minas Gerais prefere Bolsona...	Brasil 247	á 1 hora	None	Congressistas do partido em MG rejeitam a prop...	https://www.brasil247.com/regionais/sudeste/ba...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
4	O aceno de Lula à prisão de Bolsonaro	O Antagonista	á 1 hora	None	O aceno de Lula à prisão de Jair Bolsonaro pro...	https://oantagonista.uol.com.br/despertador/o-...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
5	VÍDEO : Alto representante da UE: "Li algumas ...	Euronews	á 2 horas	None	VÍDEO : O alto representante para a Política E...	https://pt.euronews.com/video/2022/05/09/alto-...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
6	Lula ou Bolsonaro? Veja 10 famosos que já decl...	iG	á 2 horas	None	Com antecedência, artistas e influenciadores d...	https://gente.ig.com.br/celebridades/2022-05-1...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
7	'Vamos ter de construir alianças', diz Lula em...	Estado de Minas	á 2 horas	None	Lula já manifestou publicamente o desejo de at...	https://www.em.com.br/app/noticia/politica/202...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
8	Na busca pelo voto feminino, companheiras de L...	Correio Braziliense	á 3 horas	None	O protagonismo de Michelle é visto por aliados...	https://www.correiobraziliense.com.br/politica...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
9	Ambulantes vendem toalhas com rostos de Lula e...	O Município	á 3 horas	None	As eleições deste ano viraram oportunidade de ...	https://omunicipio.com.br/ambulantes-vendem-to...	data:image/gif;base64,R0lGODlhAQABAIAAAP//////...
